# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[(b'CN', b'China'), (b'US', b'America')], max_length=8, null=True)),
            ],
        ),
    ]
